#!/usr/bin/env guile -e main -s
!#
(use-modules
 (ice-9 rdelim)
 (ice-9 regex)
 (srfi srfi-1))

(define (main args)
  (eval
   (let
       ((cmd (cadr args))
        (lines
         (let
             ((split-lines
               (string-split (read-delimited "") #\newline)))
           (cond
            ((string-null? (last split-lines)) (drop-right split-lines 1))
            (#t split-lines)))))
     `(map
       (lambda (line)
         (apply
          system*
          (string-split
           (regexp-substitute/global
            #f
            "[[:space:]]+"
            (simple-format
             #f
             (regexp-substitute/global
              #f
              "[{][}]"
              ,cmd
              'pre
              "~a"
              'post)
             line)
            'pre
            " "
            'post)
           #\space)))
       (quote ,lines)))
   (interaction-environment)))
